#!/bin/bash
# vim: sw=4 et

set -e

if [[ "$1" =~ ^(--help|-h)$ ]] || [ ! -n "$1" ]; then
    echo -e "$(cat << EOF
Function to run an auditable optimized cargo install command.

Requirements:
- Rust (cargo, rustc, etc.) nightly toolchain

Installing Rust:
\`\`\`zsh
# install rust
curl --proto '=https' --tlsv1.3 -sSf https://sh.rustup.rs | sh -s -- -y

# install nightly toolchain
rustup toolchain install nightly

# install rust source code
rustup component add rust-src --toolchain nightly

# install cargo-auditable and cargo-audit
# see also: https://github.com/rust-secure-code/cargo-auditable
cargo install cargo-auditable cargo-audit
\`\`\`

Usage: ${Green}$(basename "$0")${Color_Reset} opt_level crate [additional_argo_args]
EOF
)"
    exit 1
fi

opt_level="$1"
crate="$2"
shift 2 # remove first two args

set -x
RUSTFLAGS="-C target-cpu=native -C strip=symbols -Z threads=8" CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1 CARGO_PROFILE_RELEASE_LTO=true CARGO_PROFILE_RELEASE_OPT_LEVEL="$opt_level" CARGO_PROFILE_RELEASE_PANIC=abort cargo +nightly auditable install "$crate" -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target x86_64-unknown-linux-gnu $*
set +x
