#!/bin/bash
# vim: sw=4 et

# we are expecting NO argument, print help
if [ -n "$1" ]; then
    # the following line (esp. `echo -e`) is required to make color codes work
    echo -e "$(cat << EOF
List all dangling docker images.

Dangling images are images that are not referenced by any other tagged image
or in use by any created (running or stopped) container.

Requirements:
- docker

Usage: ${Green}$(basename "$0")${Color_Reset}
EOF
)"
    exit 1
fi

set -x
docker images -f "dangling=true"
