#!/bin/bash
# vim: sw=4 et

set -e

# we are expecting at least one argument, else print help
if [[ "$1" =~ ^(--help|-h)$ ]] || [ ! -n "$1" ]; then
    # the following line (esp. `echo -e`) is required to make color codes work
    echo -e "$(cat << EOF
Retreive all HTTP response headers for a given HTTP HEAD request.

Requirements:
- curl

Usage: ${Green}$(basename "$0")${Color_Reset}
EOF
)"
    exit 1
fi


# set -x:    print the exac command being executed to sterr
# --head:    switches from "GET" method to "HEAD"
# --silent:  dont print download progress to stderr
# $@:        pass all parameters directly to curl

set -x
curl --head --silent $@
