#!/bin/bash
# vim: sw=4 et

# we are expecting NO argument, print help
if [ -n "$1" ]; then
    cat << EOF
Calculate the size on disk of all dangling docker images, in MiB.

Dangling images are images that are not referenced by any other tagged image
or in use by any created (running or stopped) container.

Requirements:
- awk
- docker
- xargs

Usage: $(basename "$0")
EOF
    exit 1
fi

set -x
docker images -f "dangling=true" -q | xargs docker inspect --format='{{.Id}}: {{.Size}}' | awk '{s+=$2} END {print s/1024^2 "MiB"}'
