#!/bin/bash
# vim: sw=4 et

set -e

if [ -n "$1" ]; then
    echo -e "$(cat << EOF
List IPv4 routes.

Requirements:
- column
- ip

Usage: ${Green}$(basename "$0")${Color_Reset}
EOF
)"
    exit 1
fi

ip -4 route $* | column -t
