#!/bin/bash
# vim: sw=4 et

set -e

export Color_Reset='\033[0m'
export Green='\033[0;32m'

if [ -n "$1" ]; then
    echo -e "$(cat << EOF
List IPv4 routes.

Requirements:
- column
- ip

Usage: ${Green}$(basename "$0")${Color_Reset}
EOF
)"
    exit 1
fi

ip -6 route $* | column -t
