#!/bin/bash
# vim: sw=4 et

set -e

export Color_Reset='\033[0m'
export Green='\033[0;32m'

if [[ "$1" =~ ^(--help|-h)$ ]] || [ ! -n "$1" ]; then
    echo -e "$(cat << EOF
Function to receive X509 pem encoded certificate from a local file.

Requirements:
- openssl

Usage: ${Green}$(basename "$0")${Color_Reset} /some/path/to/file.pem
EOF
)"
    exit 1
fi

openssl x509 -noout -text -in $*
