#!/bin/bash
# vim: sw=4 et

set -e

export Color_Reset='\033[0m'
export Green='\033[0;32m'

# we are expecting NO argument, print help
if [ -n "$1" ]; then
    # the following line (esp. `echo -e`) is required to make color codes work
    echo -e "$(cat << EOF
List all docker networks and the containers that are currently attached to them.

Requirements:
- docker
- jq

Usage: ${Green}$(basename "$0")${Color_Reset}
EOF
)"
    exit 1
fi


for network in $(docker network ls --format "{{.Name}}"); do
    container_names=$(docker network inspect $network |
        jq --raw-output '.[].Containers[].Name'
    )

    network=$(docker network inspect $network --format '{{.Name}} (driver: {{.Driver}})')
    echo "$network"
    if [ -z "$container_names" ]; then
        echo -e "    No containers"
    else
        while IFS= read -r line
        do
            echo -e "    $line"
        done <<< "$container_names"
    fi
done
