#!/bin/bash
# vim: sw=4 et

set -e

export Color_Reset='\033[0m'
export Green='\033[0;32m'

if [[ "$1" =~ ^(--help|-h)$ ]] || [ ! -n "$1" ] || [ ! -n "$2" ]; then
    echo -e "$(cat << EOF
Function to make a full tls connect, printing various useful info, including
all X509 certificates (pem encoded) the remote systems has sent.

Requirements:
- openssl

Usage: ${Green}$(basename "$0")${Color_Reset} server.domain.tld port_number

Example: ${Green}$(basename "$0")${Color_Reset} google.com 443
EOF
)"
    exit 1
fi
hostName="$1"
portNumber="$2"
shift 2 # remove first two args
echo | openssl s_client -showcerts -x509_strict -connect "${hostName}:${portNumber}" -servername "$hostName"  $*
