#!/bin/bash
# vim: sw=4 et

set -e

if [ -n "$1" ]; then
    echo -e "$(cat << EOF
Function to generate DH Parameters file (pem encoded) and save it to
./dhparam.pem.

Requirements:
- openssl

Usage: ${Green}$(basename "$0")${Color_Reset}
EOF
)"
    exit 1
fi

dhparam_size=""
echo -n "dhparam size [2048]: "; read dhparam_size
if [[ "$dhparam_size" = "" ]]; then
    dhparam_size=2048
fi

openssl dhparam -out dhparam.pem "$dhparam_size"

echo
ls -l dhparam.pem
