#!/bin/bash
# vim: sw=4 et

# Wayland is used by default if XDG_SESSION_TYPE=wayland is set (ie. if you use a display manager)
#export XDG_SESSION_TYPE=wayland
# To use your monitor's DPI instead of the default of 96 DPI
export QT_WAYLAND_FORCE_DPI=physical
#export QT_QPA_PLATFORM=wayland # currently fucks up KeePassXC
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

export XDG_CURRENT_DESKTOP=sway

# Elementary/EFL
export ECORE_EVAS_ENGINE=wayland_egl
export ELM_ENGINE=wayland_egl

# Java
export _JAVA_AWT_WM_NONREPARENTING=1

# Firefox & Thunderbird
export MOZ_ENABLE_WAYLAND=1

# LibreOffice should select Wayland by default. (If not, try SAL_USE_VCLPLUGIN=gtk3).

export SDL_VIDEODRIVER=wayland

# https://github.com/swaywm/sway/issues/5008#issuecomment-585228528
export WLR_DRM_NO_MODIFIERS=1

# force wayland backend for bemenu
export BEMENU_BACKEND=wayland

# https://github.com/Alexays/Waybar/issues/21
#export XDG_CURRENT_DESKTOP=Unity

export PATH="$PATH:/home/kweis/bin:/home/kweis/.local/share/JetBrains/Toolbox/scripts"

export RUSTFLAGS="-C target-cpu=native"
export CARGO_BUILD_JOBS=10
export CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1
export CARGO_PROFILE_RELEASE_LTO=true
export CARGO_PROFILE_RELEASE_OPT_LEVEL=3
export RUSTC_WRAPPER="/home/kweis/.cargo/bin/sccache"

export SSH_AUTH_SOCK="/run/user/1000/ssh-agent.socket"

/usr/bin/sway $*

