#!/bin/bash
# Wayland is used by default if XDG_SESSION_TYPE=wayland is set (ie. if you use a display manager)
#export XDG_SESSION_TYPE=wayland
# To use your monitor's DPI instead of the default of 96 DPI
export QT_WAYLAND_FORCE_DPI=physical
#export QT_QPA_PLATFORM=wayland # currently fucks up KeePassXC
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

# Elementary/EFL
export ECORE_EVAS_ENGINE=wayland_egl
export ELM_ENGINE=wayland_egl

# Java
export _JAVA_AWT_WM_NONREPARENTING=1

# Firefox & Thunderbird
export MOZ_ENABLE_WAYLAND=1

# LibreOffice should select Wayland by default. (If not, try SAL_USE_VCLPLUGIN=gtk3).

export SDL_VIDEODRIVER=wayland

# https://github.com/swaywm/sway/issues/5008#issuecomment-585228528
export WLR_DRM_NO_MODIFIERS=1

# force wayland backend for bemenu
export BEMENU_BACKEND=wayland

# https://github.com/Alexays/Waybar/issues/21
#export XDG_CURRENT_DESKTOP=Unity

/usr/bin/sway

